/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGauge } from "./IGauge";
export type { IRouter } from "./IRouter";
export type { IVoter } from "./IVoter";
