/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20WithPermit } from "./IERC20WithPermit";
export type { ISonneMerkleDistributor } from "./ISonneMerkleDistributor";
