/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ERC20Interface,
  ERC20InterfaceInterface,
} from "../../../../contracts/libraries/SafeToken.sol/ERC20Interface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ERC20Interface__factory {
  static readonly abi = _abi;
  static createInterface(): ERC20InterfaceInterface {
    return new Interface(_abi) as ERC20InterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC20Interface {
    return new Contract(address, _abi, runner) as unknown as ERC20Interface;
  }
}
