/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as delegatorSol from "./Delegator.sol";
export type { delegatorSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { SonneMerkleDistributor } from "./SonneMerkleDistributor";
export type { TestContract } from "./TestContract";
