[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@eth-optimism/=lib/optimism/packages/"
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
