/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVoter,
  IVoterInterface,
} from "../../../../contracts/interfaces/AerodromeInterfaces.sol/IVoter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    name: "gauges",
    outputs: [
      {
        internalType: "address",
        name: "gauge",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVoter__factory {
  static readonly abi = _abi;
  static createInterface(): IVoterInterface {
    return new Interface(_abi) as IVoterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVoter {
    return new Contract(address, _abi, runner) as unknown as IVoter;
  }
}
